FROM lscr.io/linuxserver/code-server

RUN apt update
RUN apt upgrade -y

RUN apt install -y unzip zip

WORKDIR /config/workspace

RUN curl -s "https://get.sdkman.io" | bash

RUN /bin/bash -c "source /config/.sdkman/bin/sdkman-init.sh; sdk install java 11.0.12-open; sdk install sbt" 
